name = "tothread-webapp"
main = "index.js"
compatibility_date = "2025-11-25"

[vars]
# Add non-secret configuration here as needed later (e.g., API base paths).
GOOGLE_CLIENT_ID = "130905058858-07408ql1m1nonfoaftc415t0er256n5v.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "TOTHREAD_KV"
id = "0d1802d813da4c7fa7cfdf62be0289c5"
